### ISSUE TITLE
Issue with  DirectorySecrets.from_path() constructor

### ISSUE THREAD

**Issue by jevhen-ponomarenko** [hynek/environ-config#45]
Hi,

I think there might be a bug in the `from_path()` constructor of `DirectorySecrets` class. 

## Code to reproduce
```python
from environ import secrets
import environ
dir_secrets = secrets.DirectorySecrets.from_path("/run/secrets")

@environ.config(prefix="")
class TestSettings:
    dummy = dir_secrets.secret()

a = TestSettings.from_environ()
```

Fails with an exception: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/venv/lib/python3.10/site-packages/environ/_environ_config.py", line 93, in from_environ_fnc
    return __to_config(cls, environ)
  File "/opt/venv/lib/python3.10/site-packages/environ/_environ_config.py", line 307, in to_config
    return _to_config_recurse(config_cls, environ, app_prefix)
  File "/opt/venv/lib/python3.10/site-packages/environ/_environ_config.py", line 268, in _to_config_recurse
    got[name] = getter(environ, attr_obj.metadata, prefixes, name)
  File "/opt/venv/lib/python3.10/site-packages/environ/secrets/__init__.py", line 189, in _get
    secrets_dir = environ.get(self._env_name, self.secrets_dir)
  File "/usr/local/lib/python3.10/_collections_abc.py", line 819, in get
    return self[key]
  File "/usr/local/lib/python3.10/os.py", line 676, in __getitem__
    value = self._data[self.encodekey(key)]
  File "/usr/local/lib/python3.10/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType
```

I think it has to do with the fact that `_env_name` attribute is used to get default `secret_dir` value. `_env_name` is None by default, hence the error. [Code in question](https://github.com/hynek/environ-config/blob/ffaa673e7735981169ce0cce4327eee1843a2792/src/environ/secrets/__init__.py#L183).

```python
def _get(self, environ, metadata, prefix, name):
        ce = metadata[CNF_KEY]
        # conventions for file naming might be different
        # than for environment variables, so we don't call .upper()
        filename = ce.name or "_".join(prefix[1:] + (name,))

        secrets_dir = environ.get(self._env_name, self.secrets_dir) < ---- failing line
        secret_path = os.path.join(secrets_dir, filename)
        log.debug("looking for secret in file '%s'.", secret_path)

        try:
            with _open_file(secret_path) as f:
                val = f.read()
            return _SecretStr(val)
        except FileOpenError:
            return _get_default_secret(filename, ce.default)
```

## Workaround

I was able to overcome the issue using `from_path_in_env()` with a default value:
```python
dir_secrets = secrets.DirectorySecrets.from_path_in_env(
    env_name="dummy", default="/run/secrets"
)
```

**Comment by hynek** [comment]
Ah that's a fun one! Regular dictionaries allow for accessing `None`, but os.environ does not!
